{
 "title": "PHP USDT/uprpbe SAMPLES",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ebpf_exporter samples for PHP",
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 1 },
   "options": {
    "content": "これはPHPの各種メトリクスをebpf exporterで取得してビジュアライズするサンプルです。\n\nUSDT、uprobeなどのトレースポイントを利用して得られるデータの例を示します。\n"
   }
  },
  { "title": "Uprobe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "memcached value length distribution(set)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ebpf_exporter_memcached_set_val_length_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "memcached value length percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ebpf_exporter_memcached_set_val_length_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ebpf_exporter_memcached_set_val_length_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ebpf_exporter_memcached_set_val_length_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "USDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PHP Request time from startup to shutdown",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ebpf_exporter_php_request_time_sec_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ebpf_exporter_php_request_time_sec_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(ebpf_exporter_php_request_time_sec_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ebpf_exporter_php_request_time_sec_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "PHP USDT Compile DIR Total",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ebpf_exporter_php_compile_file_total",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "PHP USDT Exception Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_php_exception_thrown_total[10m])",
     "legendFormat": "{{class}}"
    }
   ]
  }
 ]
}